/* ------------------------------------------------------------ 			*/
/* TITLE:		 	Collect all IP/OP procedures for major joint patients	*/
/* AUTHOR:		 	Ian McCarthy											*/
/* 				 	Emory University										*/
/* DATE CREATED: 	12/31/2018												*/
/* DATE EDITED:  	4/27/2021												*/
/* CODE FILE ORDER: 2 of 8  												*/
/* OUTPUT:			AllProcedures_2007_2018									*/
/* ------------------------------------------------------------ 			*/


/* Create Table of Inpatient and Outpatient Stays for each year */
DATA WORK.InpatientStays_2007;
	SET	RIF2007.INPATIENT_CLAIMS_01
  		RIF2007.INPATIENT_CLAIMS_02
		RIF2007.INPATIENT_CLAIMS_03
		RIF2007.INPATIENT_CLAIMS_04
		RIF2007.INPATIENT_CLAIMS_05
		RIF2007.INPATIENT_CLAIMS_06
		RIF2007.INPATIENT_CLAIMS_07
		RIF2007.INPATIENT_CLAIMS_08
		RIF2007.INPATIENT_CLAIMS_09
		RIF2007.INPATIENT_CLAIMS_10
		RIF2007.INPATIENT_CLAIMS_11
		RIF2007.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2007;
	SET	RIF2007.OUTPATIENT_CLAIMS_01
  		RIF2007.OUTPATIENT_CLAIMS_02
		RIF2007.OUTPATIENT_CLAIMS_03
		RIF2007.OUTPATIENT_CLAIMS_04
		RIF2007.OUTPATIENT_CLAIMS_05
		RIF2007.OUTPATIENT_CLAIMS_06
		RIF2007.OUTPATIENT_CLAIMS_07
		RIF2007.OUTPATIENT_CLAIMS_08
		RIF2007.OUTPATIENT_CLAIMS_09
		RIF2007.OUTPATIENT_CLAIMS_10
		RIF2007.OUTPATIENT_CLAIMS_11
		RIF2007.OUTPATIENT_CLAIMS_12;
RUN;


DATA WORK.InpatientStays_2008;
	SET	RIF2008.INPATIENT_CLAIMS_01
  		RIF2008.INPATIENT_CLAIMS_02
		RIF2008.INPATIENT_CLAIMS_03
		RIF2008.INPATIENT_CLAIMS_04
		RIF2008.INPATIENT_CLAIMS_05
		RIF2008.INPATIENT_CLAIMS_06
		RIF2008.INPATIENT_CLAIMS_07
		RIF2008.INPATIENT_CLAIMS_08
		RIF2008.INPATIENT_CLAIMS_09
		RIF2008.INPATIENT_CLAIMS_10
		RIF2008.INPATIENT_CLAIMS_11
		RIF2008.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2008;
	SET	RIF2008.OUTPATIENT_CLAIMS_01
  		RIF2008.OUTPATIENT_CLAIMS_02
		RIF2008.OUTPATIENT_CLAIMS_03
		RIF2008.OUTPATIENT_CLAIMS_04
		RIF2008.OUTPATIENT_CLAIMS_05
		RIF2008.OUTPATIENT_CLAIMS_06
		RIF2008.OUTPATIENT_CLAIMS_07
		RIF2008.OUTPATIENT_CLAIMS_08
		RIF2008.OUTPATIENT_CLAIMS_09
		RIF2008.OUTPATIENT_CLAIMS_10
		RIF2008.OUTPATIENT_CLAIMS_11
		RIF2008.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.InpatientStays_2009;
	SET	RIF2009.INPATIENT_CLAIMS_01
  		RIF2009.INPATIENT_CLAIMS_02
		RIF2009.INPATIENT_CLAIMS_03
		RIF2009.INPATIENT_CLAIMS_04
		RIF2009.INPATIENT_CLAIMS_05
		RIF2009.INPATIENT_CLAIMS_06
		RIF2009.INPATIENT_CLAIMS_07
		RIF2009.INPATIENT_CLAIMS_08
		RIF2009.INPATIENT_CLAIMS_09
		RIF2009.INPATIENT_CLAIMS_10
		RIF2009.INPATIENT_CLAIMS_11
		RIF2009.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2009;
	SET	RIF2009.OUTPATIENT_CLAIMS_01
  		RIF2009.OUTPATIENT_CLAIMS_02
		RIF2009.OUTPATIENT_CLAIMS_03
		RIF2009.OUTPATIENT_CLAIMS_04
		RIF2009.OUTPATIENT_CLAIMS_05
		RIF2009.OUTPATIENT_CLAIMS_06
		RIF2009.OUTPATIENT_CLAIMS_07
		RIF2009.OUTPATIENT_CLAIMS_08
		RIF2009.OUTPATIENT_CLAIMS_09
		RIF2009.OUTPATIENT_CLAIMS_10
		RIF2009.OUTPATIENT_CLAIMS_11
		RIF2009.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.InpatientStays_2010;
	SET	RIF2010.INPATIENT_CLAIMS_01
  		RIF2010.INPATIENT_CLAIMS_02
		RIF2010.INPATIENT_CLAIMS_03
		RIF2010.INPATIENT_CLAIMS_04
		RIF2010.INPATIENT_CLAIMS_05
		RIF2010.INPATIENT_CLAIMS_06
		RIF2010.INPATIENT_CLAIMS_07
		RIF2010.INPATIENT_CLAIMS_08
		RIF2010.INPATIENT_CLAIMS_09
		RIF2010.INPATIENT_CLAIMS_10
		RIF2010.INPATIENT_CLAIMS_11
		RIF2010.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2010;
	SET	RIF2010.OUTPATIENT_CLAIMS_01
  		RIF2010.OUTPATIENT_CLAIMS_02
		RIF2010.OUTPATIENT_CLAIMS_03
		RIF2010.OUTPATIENT_CLAIMS_04
		RIF2010.OUTPATIENT_CLAIMS_05
		RIF2010.OUTPATIENT_CLAIMS_06
		RIF2010.OUTPATIENT_CLAIMS_07
		RIF2010.OUTPATIENT_CLAIMS_08
		RIF2010.OUTPATIENT_CLAIMS_09
		RIF2010.OUTPATIENT_CLAIMS_10
		RIF2010.OUTPATIENT_CLAIMS_11
		RIF2010.OUTPATIENT_CLAIMS_12;
RUN;


DATA WORK.InpatientStays_2011;
	SET	RIF2011.INPATIENT_CLAIMS_01
  		RIF2011.INPATIENT_CLAIMS_02
		RIF2011.INPATIENT_CLAIMS_03
		RIF2011.INPATIENT_CLAIMS_04
		RIF2011.INPATIENT_CLAIMS_05
		RIF2011.INPATIENT_CLAIMS_06
		RIF2011.INPATIENT_CLAIMS_07
		RIF2011.INPATIENT_CLAIMS_08
		RIF2011.INPATIENT_CLAIMS_09
		RIF2011.INPATIENT_CLAIMS_10
		RIF2011.INPATIENT_CLAIMS_11
		RIF2011.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2011;
	SET	RIF2011.OUTPATIENT_CLAIMS_01
  		RIF2011.OUTPATIENT_CLAIMS_02
		RIF2011.OUTPATIENT_CLAIMS_03
		RIF2011.OUTPATIENT_CLAIMS_04
		RIF2011.OUTPATIENT_CLAIMS_05
		RIF2011.OUTPATIENT_CLAIMS_06
		RIF2011.OUTPATIENT_CLAIMS_07
		RIF2011.OUTPATIENT_CLAIMS_08
		RIF2011.OUTPATIENT_CLAIMS_09
		RIF2011.OUTPATIENT_CLAIMS_10
		RIF2011.OUTPATIENT_CLAIMS_11
		RIF2011.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.InpatientStays_2012;
	SET	RIF2012.INPATIENT_CLAIMS_01
  		RIF2012.INPATIENT_CLAIMS_02
		RIF2012.INPATIENT_CLAIMS_03
		RIF2012.INPATIENT_CLAIMS_04
		RIF2012.INPATIENT_CLAIMS_05
		RIF2012.INPATIENT_CLAIMS_06
		RIF2012.INPATIENT_CLAIMS_07
		RIF2012.INPATIENT_CLAIMS_08
		RIF2012.INPATIENT_CLAIMS_09
		RIF2012.INPATIENT_CLAIMS_10
		RIF2012.INPATIENT_CLAIMS_11
		RIF2012.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2012;
	SET	RIF2012.OUTPATIENT_CLAIMS_01
  		RIF2012.OUTPATIENT_CLAIMS_02
		RIF2012.OUTPATIENT_CLAIMS_03
		RIF2012.OUTPATIENT_CLAIMS_04
		RIF2012.OUTPATIENT_CLAIMS_05
		RIF2012.OUTPATIENT_CLAIMS_06
		RIF2012.OUTPATIENT_CLAIMS_07
		RIF2012.OUTPATIENT_CLAIMS_08
		RIF2012.OUTPATIENT_CLAIMS_09
		RIF2012.OUTPATIENT_CLAIMS_10
		RIF2012.OUTPATIENT_CLAIMS_11
		RIF2012.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.InpatientStays_2013;
	SET	RIF2013.INPATIENT_CLAIMS_01
  		RIF2013.INPATIENT_CLAIMS_02
		RIF2013.INPATIENT_CLAIMS_03
		RIF2013.INPATIENT_CLAIMS_04
		RIF2013.INPATIENT_CLAIMS_05
		RIF2013.INPATIENT_CLAIMS_06
		RIF2013.INPATIENT_CLAIMS_07
		RIF2013.INPATIENT_CLAIMS_08
		RIF2013.INPATIENT_CLAIMS_09
		RIF2013.INPATIENT_CLAIMS_10
		RIF2013.INPATIENT_CLAIMS_11
		RIF2013.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2013;
	SET	RIF2013.OUTPATIENT_CLAIMS_01
  		RIF2013.OUTPATIENT_CLAIMS_02
		RIF2013.OUTPATIENT_CLAIMS_03
		RIF2013.OUTPATIENT_CLAIMS_04
		RIF2013.OUTPATIENT_CLAIMS_05
		RIF2013.OUTPATIENT_CLAIMS_06
		RIF2013.OUTPATIENT_CLAIMS_07
		RIF2013.OUTPATIENT_CLAIMS_08
		RIF2013.OUTPATIENT_CLAIMS_09
		RIF2013.OUTPATIENT_CLAIMS_10
		RIF2013.OUTPATIENT_CLAIMS_11
		RIF2013.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.InpatientStays_2014;
	SET	RIF2014.INPATIENT_CLAIMS_01
  		RIF2014.INPATIENT_CLAIMS_02
		RIF2014.INPATIENT_CLAIMS_03
		RIF2014.INPATIENT_CLAIMS_04
		RIF2014.INPATIENT_CLAIMS_05
		RIF2014.INPATIENT_CLAIMS_06
		RIF2014.INPATIENT_CLAIMS_07
		RIF2014.INPATIENT_CLAIMS_08
		RIF2014.INPATIENT_CLAIMS_09
		RIF2014.INPATIENT_CLAIMS_10
		RIF2014.INPATIENT_CLAIMS_11
		RIF2014.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2014;
	SET	RIF2014.OUTPATIENT_CLAIMS_01
  		RIF2014.OUTPATIENT_CLAIMS_02
		RIF2014.OUTPATIENT_CLAIMS_03
		RIF2014.OUTPATIENT_CLAIMS_04
		RIF2014.OUTPATIENT_CLAIMS_05
		RIF2014.OUTPATIENT_CLAIMS_06
		RIF2014.OUTPATIENT_CLAIMS_07
		RIF2014.OUTPATIENT_CLAIMS_08
		RIF2014.OUTPATIENT_CLAIMS_09
		RIF2014.OUTPATIENT_CLAIMS_10
		RIF2014.OUTPATIENT_CLAIMS_11
		RIF2014.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.InpatientStays_2015;
	SET	RIF2015.INPATIENT_CLAIMS_01
  		RIF2015.INPATIENT_CLAIMS_02
		RIF2015.INPATIENT_CLAIMS_03
		RIF2015.INPATIENT_CLAIMS_04
		RIF2015.INPATIENT_CLAIMS_05
		RIF2015.INPATIENT_CLAIMS_06
		RIF2015.INPATIENT_CLAIMS_07
		RIF2015.INPATIENT_CLAIMS_08
		RIF2015.INPATIENT_CLAIMS_09
		RIF2015.INPATIENT_CLAIMS_10
		RIF2015.INPATIENT_CLAIMS_11
		RIF2015.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2015;
	SET	RIF2015.OUTPATIENT_CLAIMS_01
  		RIF2015.OUTPATIENT_CLAIMS_02
		RIF2015.OUTPATIENT_CLAIMS_03
		RIF2015.OUTPATIENT_CLAIMS_04
		RIF2015.OUTPATIENT_CLAIMS_05
		RIF2015.OUTPATIENT_CLAIMS_06
		RIF2015.OUTPATIENT_CLAIMS_07
		RIF2015.OUTPATIENT_CLAIMS_08
		RIF2015.OUTPATIENT_CLAIMS_09
		RIF2015.OUTPATIENT_CLAIMS_10
		RIF2015.OUTPATIENT_CLAIMS_11
		RIF2015.OUTPATIENT_CLAIMS_12;
RUN;



DATA WORK.InpatientStays_2016;
	SET	RIF2016.INPATIENT_CLAIMS_01
  		RIF2016.INPATIENT_CLAIMS_02
		RIF2016.INPATIENT_CLAIMS_03
		RIF2016.INPATIENT_CLAIMS_04
		RIF2016.INPATIENT_CLAIMS_05
		RIF2016.INPATIENT_CLAIMS_06
		RIF2016.INPATIENT_CLAIMS_07
		RIF2016.INPATIENT_CLAIMS_08
		RIF2016.INPATIENT_CLAIMS_09
		RIF2016.INPATIENT_CLAIMS_10
		RIF2016.INPATIENT_CLAIMS_11
		RIF2016.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2016;
	SET	RIF2016.OUTPATIENT_CLAIMS_01
  		RIF2016.OUTPATIENT_CLAIMS_02
		RIF2016.OUTPATIENT_CLAIMS_03
		RIF2016.OUTPATIENT_CLAIMS_04
		RIF2016.OUTPATIENT_CLAIMS_05
		RIF2016.OUTPATIENT_CLAIMS_06
		RIF2016.OUTPATIENT_CLAIMS_07
		RIF2016.OUTPATIENT_CLAIMS_08
		RIF2016.OUTPATIENT_CLAIMS_09
		RIF2016.OUTPATIENT_CLAIMS_10
		RIF2016.OUTPATIENT_CLAIMS_11
		RIF2016.OUTPATIENT_CLAIMS_12;
RUN;



DATA WORK.InpatientStays_2017;
	SET	RIF2017.INPATIENT_CLAIMS_01
  		RIF2017.INPATIENT_CLAIMS_02
		RIF2017.INPATIENT_CLAIMS_03
		RIF2017.INPATIENT_CLAIMS_04
		RIF2017.INPATIENT_CLAIMS_05
		RIF2017.INPATIENT_CLAIMS_06
		RIF2017.INPATIENT_CLAIMS_07
		RIF2017.INPATIENT_CLAIMS_08
		RIF2017.INPATIENT_CLAIMS_09
		RIF2017.INPATIENT_CLAIMS_10
		RIF2017.INPATIENT_CLAIMS_11
		RIF2017.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2017;
	SET	RIF2017.OUTPATIENT_CLAIMS_01
  		RIF2017.OUTPATIENT_CLAIMS_02
		RIF2017.OUTPATIENT_CLAIMS_03
		RIF2017.OUTPATIENT_CLAIMS_04
		RIF2017.OUTPATIENT_CLAIMS_05
		RIF2017.OUTPATIENT_CLAIMS_06
		RIF2017.OUTPATIENT_CLAIMS_07
		RIF2017.OUTPATIENT_CLAIMS_08
		RIF2017.OUTPATIENT_CLAIMS_09
		RIF2017.OUTPATIENT_CLAIMS_10
		RIF2017.OUTPATIENT_CLAIMS_11
		RIF2017.OUTPATIENT_CLAIMS_12;
RUN;



DATA WORK.InpatientStays_2018;
	SET	RIF2018.INPATIENT_CLAIMS_01
  		RIF2018.INPATIENT_CLAIMS_02
		RIF2018.INPATIENT_CLAIMS_03
		RIF2018.INPATIENT_CLAIMS_04
		RIF2018.INPATIENT_CLAIMS_05
		RIF2018.INPATIENT_CLAIMS_06
		RIF2018.INPATIENT_CLAIMS_07
		RIF2018.INPATIENT_CLAIMS_08
		RIF2018.INPATIENT_CLAIMS_09
		RIF2018.INPATIENT_CLAIMS_10
		RIF2018.INPATIENT_CLAIMS_11
		RIF2018.INPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientStays_2018;
	SET	RIF2018.OUTPATIENT_CLAIMS_01
  		RIF2018.OUTPATIENT_CLAIMS_02
		RIF2018.OUTPATIENT_CLAIMS_03
		RIF2018.OUTPATIENT_CLAIMS_04
		RIF2018.OUTPATIENT_CLAIMS_05
		RIF2018.OUTPATIENT_CLAIMS_06
		RIF2018.OUTPATIENT_CLAIMS_07
		RIF2018.OUTPATIENT_CLAIMS_08
		RIF2018.OUTPATIENT_CLAIMS_09
		RIF2018.OUTPATIENT_CLAIMS_10
		RIF2018.OUTPATIENT_CLAIMS_11
		RIF2018.OUTPATIENT_CLAIMS_12;
RUN;


/* Collect claims among major joint replacement patients (2007-2008)*/
%LET year_data=2008;

PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.NCH_BENE_DSCHRG_DT, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		CASE
			WHEN a.ORG_NPI_NUM NE '' AND a.ORG_NPI_NUM NE '0000000000' THEN a.ORG_NPI_NUM
			WHEN a.ORG_NPI_NUM='' OR a.ORG_NPI_NUM='0000000000' THEN b.NPI
		ELSE ''
		END AS ORG_NPI_NUM,
		a.CLM_DRG_CD, a.ADMTG_DGNS_CD, a.ICD_DGNS_CD1, a.PRNCPAL_DGNS_CD, a.ICD_PRCDR_CD1, 
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT,
		a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, a.ICD_DGNS_CD6, a.ICD_DGNS_CD7,
		a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data AS a
	LEFT JOIN IMC969SL.PRVN_NPI_Merge_&year_data AS b
		ON a.PRVDR_NUM=b.PRVDR_NUM
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS d
		ON a.BENE_ID=d.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		CASE
			WHEN a.ORG_NPI_NUM NE '' AND a.ORG_NPI_NUM NE '0000000000' THEN a.ORG_NPI_NUM
			WHEN a.ORG_NPI_NUM='' OR a.ORG_NPI_NUM='0000000000' THEN b.NPI
		ELSE ''
		END AS ORG_NPI_NUM,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN IMC969SL.PRVN_NPI_Merge_&year_data AS b
		ON a.PRVDR_NUM=b.PRVDR_NUM
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;



/* Collect claims among major joint replacement patients (2009-2018)*/
%LET year_data=2009;
PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, CLM_ID, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, CLM_DRG_CD, 
	    ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		CLM_PMT_AMT, CLM_TOT_CHRG_AMT,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, 
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data as a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;



%LET year_data=2010;
PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, CLM_ID, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, CLM_DRG_CD, 
	    ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		CLM_PMT_AMT, CLM_TOT_CHRG_AMT,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, 
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data as a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;


%LET year_data=2011;
PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, CLM_ID, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, CLM_DRG_CD, 
	    ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		CLM_PMT_AMT, CLM_TOT_CHRG_AMT,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, 
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data as a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;


%LET year_data=2012;
PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, CLM_ID, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, CLM_DRG_CD, 
	    ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		CLM_PMT_AMT, CLM_TOT_CHRG_AMT,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, 
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data as a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;


%LET year_data=2013;
PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, CLM_ID, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, CLM_DRG_CD, 
	    ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		CLM_PMT_AMT, CLM_TOT_CHRG_AMT,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data as a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;


%LET year_data=2014;
PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, CLM_ID, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, CLM_DRG_CD, 
	    ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		CLM_PMT_AMT, CLM_TOT_CHRG_AMT,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data as a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;


%LET year_data=2015;
PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, CLM_ID, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, CLM_DRG_CD, 
	    ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		CLM_PMT_AMT, CLM_TOT_CHRG_AMT,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, 
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data as a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;


%LET year_data=2016;
PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, CLM_ID, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, CLM_DRG_CD, 
	    ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		CLM_PMT_AMT, CLM_TOT_CHRG_AMT,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data as a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;


%LET year_data=2017;
PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, CLM_ID, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, CLM_DRG_CD, 
	    ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		CLM_PMT_AMT, CLM_TOT_CHRG_AMT,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data as a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;


%LET year_data=2018;
PROC SQL;
	DROP TABLE WORK.IP_Procedures_&year_data;
	CREATE TABLE WORK.IP_Procedures_&year_data AS
	SELECT a.BENE_ID, CLM_ID, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, CLM_DRG_CD, 
	    ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		CLM_PMT_AMT, CLM_TOT_CHRG_AMT,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, 
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS, 'Inpatient' AS Type
	FROM WORK.InpatientStays_&year_data as a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS c
		ON a.BENE_ID=c.BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE WORK.OP_Procedures_&year_data;
	CREATE TABLE WORK.OP_Procedures_&year_data AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, 'Outpatient' AS Type
	FROM WORK.OutpatientStays_&year_data AS a
	LEFT JOIN (SELECT DISTINCT BENE_ID FROM IMC969SL.MajorJointPatients_ByYear WHERE Year<=&year_data & Year>(&year_data-2) ) AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

DATA IMC969SL.AllProcedures_&year_data;
	SET	WORK.IP_Procedures_&year_data
  		WORK.OP_Procedures_&year_data;
RUN;