/* ------------------------------------------------------------ 	*/
/* TITLE:		 	Calculate zip code distances					*/
/* AUTHOR:		 	Ian McCarthy									*/
/* 				 	Emory University								*/
/* DATE CREATED: 	12/16/2021										*/
/* DATE EDITED:  	12/16/2021										*/
/* CODE FILE ORDER: 8 of 8											*/
/* OUTPUT:			DistancePhy_2009-2018      				     	*/
/* 					DistancePatient_2009-2018      			     	*/
/* ------------------------------------------------------------ 	*/

/* ------------------------------------------------------------ 	*/
/* 2009 Data */
/* ------------------------------------------------------------ 	*/
DATA WORK.InpatientStays_2009;
	SET	RIF2009.INPATIENT_CLAIMS_01
  		RIF2009.INPATIENT_CLAIMS_02
		RIF2009.INPATIENT_CLAIMS_03
		RIF2009.INPATIENT_CLAIMS_04
		RIF2009.INPATIENT_CLAIMS_05
		RIF2009.INPATIENT_CLAIMS_06
		RIF2009.INPATIENT_CLAIMS_07
		RIF2009.INPATIENT_CLAIMS_08
		RIF2009.INPATIENT_CLAIMS_09
		RIF2009.INPATIENT_CLAIMS_10
		RIF2009.INPATIENT_CLAIMS_11
		RIF2009.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
DROP TABLE WORK.Hospital_Location;
CREATE TABLE WORK.Hospital_Location AS
	SELECT ORG_NPI_NUM AS Hosp_NPI, PRVDR_NUM AS Provider_Number,
		PRVDR_STATE_CD AS Hosp_State, SUBSTR(CLM_SRVC_FAC_ZIP_CD,1,5) AS Hosp_Zip,
		count(*) AS Claim_Count
	FROM WORK.InpatientStays_2009
	GROUP BY Hosp_NPI, PRVDR_NUM, Hosp_State, Hosp_Zip;
QUIT;

PROC SQL;
DROP TABLE PL027710.Hospital_Location_2009;
CREATE TABLE PL027710.Hospital_Location_2009 AS
	SELECT a.*, b.FACILITY_NAME AS Hosp_Name_POS, b.FIPS_CNTY AS Hosp_County_POS, b.FIPS_STATE AS Hosp_State_POS,
		b.PROV_NUM AS Provider_Number, b.PARENT_PROV_NUM AS Parent_Provider_Number, b.ZIP_CD AS Hosp_Zip_POS
	FROM WORK.Hospital_Location AS a
	LEFT JOIN PROVIDER.POS_2009 AS b
	ON a.Provider_Number=b.PROV_NUM;
QUIT;



PROC SQL;
  DROP TABLE WORK.PhyLocation1;
  CREATE TABLE WORK.PhyLocation1 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_01
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation2;
  CREATE TABLE WORK.PhyLocation2 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_02
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation3;
  CREATE TABLE WORK.PhyLocation3 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_03
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation4;
  CREATE TABLE WORK.PhyLocation4 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_04
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation5;
  CREATE TABLE WORK.PhyLocation5 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_05
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation6;
  CREATE TABLE WORK.PhyLocation6 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_06
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation7;
  CREATE TABLE WORK.PhyLocation7 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_07
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation8;
  CREATE TABLE WORK.PhyLocation8 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_08
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation9;
  CREATE TABLE WORK.PhyLocation9 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_09
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation10;
  CREATE TABLE WORK.PhyLocation10 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_10
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation11;
  CREATE TABLE WORK.PhyLocation11 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_11
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation12;
  CREATE TABLE WORK.PhyLocation12 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2009.BCARRIER_LINE_12
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

DATA WORK.PhyLocation;
	SET	WORK.PhyLocation1
  		WORK.PhyLocation2
		WORK.PhyLocation3
		WORK.PhyLocation4
		WORK.PhyLocation5
		WORK.PhyLocation6
		WORK.PhyLocation7
		WORK.PhyLocation8
		WORK.PhyLocation9
		WORK.PhyLocation10
		WORK.PhyLocation11
		WORK.PhyLocation12;
RUN;


PROC SQL;
  DROP TABLE PL027710.PhyLocation_2009;
  CREATE TABLE PL027710.PhyLocation_2009 AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;




/* ------------------------------------------------------------ 	*/
/* 2010 Data */
/* ------------------------------------------------------------ 	*/
DATA WORK.InpatientStays_2010;
	SET	RIF2010.INPATIENT_CLAIMS_01
  		RIF2010.INPATIENT_CLAIMS_02
		RIF2010.INPATIENT_CLAIMS_03
		RIF2010.INPATIENT_CLAIMS_04
		RIF2010.INPATIENT_CLAIMS_05
		RIF2010.INPATIENT_CLAIMS_06
		RIF2010.INPATIENT_CLAIMS_07
		RIF2010.INPATIENT_CLAIMS_08
		RIF2010.INPATIENT_CLAIMS_09
		RIF2010.INPATIENT_CLAIMS_10
		RIF2010.INPATIENT_CLAIMS_11
		RIF2010.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
DROP TABLE WORK.Hospital_Location;
CREATE TABLE WORK.Hospital_Location AS
	SELECT ORG_NPI_NUM AS Hosp_NPI, PRVDR_NUM AS Provider_Number,
		PRVDR_STATE_CD AS Hosp_State, SUBSTR(CLM_SRVC_FAC_ZIP_CD,1,5) AS Hosp_Zip,
		count(*) AS Claim_Count
	FROM WORK.InpatientStays_2010
	GROUP BY Hosp_NPI, PRVDR_NUM, Hosp_State, Hosp_Zip;
QUIT;

PROC SQL;
DROP TABLE PL027710.Hospital_Location_2010;
CREATE TABLE PL027710.Hospital_Location_2010 AS
	SELECT a.*, b.FACILITY_NAME AS Hosp_Name_POS, b.FIPS_CNTY AS Hosp_County_POS, b.FIPS_STATE AS Hosp_State_POS,
		b.PROV_NUM AS Provider_Number, b.PARENT_PROV_NUM AS Parent_Provider_Number, b.ZIP_CD AS Hosp_Zip_POS
	FROM WORK.Hospital_Location AS a
	LEFT JOIN PROVIDER.POS_2010 AS b
	ON a.Provider_Number=b.PROV_NUM;
QUIT;


PROC SQL;
  DROP TABLE WORK.PhyLocation1;
  CREATE TABLE WORK.PhyLocation1 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_01
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation2;
  CREATE TABLE WORK.PhyLocation2 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_02
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation3;
  CREATE TABLE WORK.PhyLocation3 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_03
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation4;
  CREATE TABLE WORK.PhyLocation4 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_04
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation5;
  CREATE TABLE WORK.PhyLocation5 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_05
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation6;
  CREATE TABLE WORK.PhyLocation6 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_06
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation7;
  CREATE TABLE WORK.PhyLocation7 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_07
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation8;
  CREATE TABLE WORK.PhyLocation8 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_08
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation9;
  CREATE TABLE WORK.PhyLocation9 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_09
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation10;
  CREATE TABLE WORK.PhyLocation10 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_10
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation11;
  CREATE TABLE WORK.PhyLocation11 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_11
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation12;
  CREATE TABLE WORK.PhyLocation12 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2010.BCARRIER_LINE_12
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

DATA WORK.PhyLocation;
	SET	WORK.PhyLocation1
  		WORK.PhyLocation2
		WORK.PhyLocation3
		WORK.PhyLocation4
		WORK.PhyLocation5
		WORK.PhyLocation6
		WORK.PhyLocation7
		WORK.PhyLocation8
		WORK.PhyLocation9
		WORK.PhyLocation10
		WORK.PhyLocation11
		WORK.PhyLocation12;
RUN;


PROC SQL;
  DROP TABLE PL027710.PhyLocation_2010;
  CREATE TABLE PL027710.PhyLocation_2010 AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;




/* ------------------------------------------------------------ 	*/
/* 2011 Data */
/* ------------------------------------------------------------ 	*/
DATA WORK.InpatientStays_2011;
	SET	RIF2011.INPATIENT_CLAIMS_01
  		RIF2011.INPATIENT_CLAIMS_02
		RIF2011.INPATIENT_CLAIMS_03
		RIF2011.INPATIENT_CLAIMS_04
		RIF2011.INPATIENT_CLAIMS_05
		RIF2011.INPATIENT_CLAIMS_06
		RIF2011.INPATIENT_CLAIMS_07
		RIF2011.INPATIENT_CLAIMS_08
		RIF2011.INPATIENT_CLAIMS_09
		RIF2011.INPATIENT_CLAIMS_10
		RIF2011.INPATIENT_CLAIMS_11
		RIF2011.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
DROP TABLE WORK.Hospital_Location;
CREATE TABLE WORK.Hospital_Location AS
	SELECT ORG_NPI_NUM AS Hosp_NPI, PRVDR_NUM AS Provider_Number,
		PRVDR_STATE_CD AS Hosp_State, SUBSTR(CLM_SRVC_FAC_ZIP_CD,1,5) AS Hosp_Zip,
		count(*) AS Claim_Count
	FROM WORK.InpatientStays_2011
	GROUP BY Hosp_NPI, PRVDR_NUM, Hosp_State, Hosp_Zip;
QUIT;

PROC SQL;
DROP TABLE PL027710.Hospital_Location_2011;
CREATE TABLE PL027710.Hospital_Location_2011 AS
	SELECT a.*, b.FAC_NAME AS Hosp_Name_POS, b.FIPS_CNTY_CD AS Hosp_County_POS, b.FIPS_STATE_CD AS Hosp_State_POS,
		b.PRVDR_NUM AS Provider_Number, b.PARENT_PROVIDER_NUMBER AS Parent_Provider_Number, b.ZIP_CD AS Hosp_Zip_POS
	FROM WORK.Hospital_Location AS a
	LEFT JOIN PROVIDER.POS_2011 AS b
	ON a.Provider_Number=b.PRVDR_NUM;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation1;
  CREATE TABLE WORK.PhyLocation1 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_01
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation2;
  CREATE TABLE WORK.PhyLocation2 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_02
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation3;
  CREATE TABLE WORK.PhyLocation3 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_03
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation4;
  CREATE TABLE WORK.PhyLocation4 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_04
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation5;
  CREATE TABLE WORK.PhyLocation5 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_05
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation6;
  CREATE TABLE WORK.PhyLocation6 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_06
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation7;
  CREATE TABLE WORK.PhyLocation7 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_07
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation8;
  CREATE TABLE WORK.PhyLocation8 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_08
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation9;
  CREATE TABLE WORK.PhyLocation9 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_09
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation10;
  CREATE TABLE WORK.PhyLocation10 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_10
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation11;
  CREATE TABLE WORK.PhyLocation11 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_11
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation12;
  CREATE TABLE WORK.PhyLocation12 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2011.BCARRIER_LINE_12
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

DATA WORK.PhyLocation;
	SET	WORK.PhyLocation1
  		WORK.PhyLocation2
		WORK.PhyLocation3
		WORK.PhyLocation4
		WORK.PhyLocation5
		WORK.PhyLocation6
		WORK.PhyLocation7
		WORK.PhyLocation8
		WORK.PhyLocation9
		WORK.PhyLocation10
		WORK.PhyLocation11
		WORK.PhyLocation12;
RUN;


PROC SQL;
  DROP TABLE PL027710.PhyLocation_2011;
  CREATE TABLE PL027710.PhyLocation_2011 AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;




/* ------------------------------------------------------------ 	*/
/* 2012 Data */
/* ------------------------------------------------------------ 	*/
DATA WORK.InpatientStays_2012;
	SET	RIF2012.INPATIENT_CLAIMS_01
  		RIF2012.INPATIENT_CLAIMS_02
		RIF2012.INPATIENT_CLAIMS_03
		RIF2012.INPATIENT_CLAIMS_04
		RIF2012.INPATIENT_CLAIMS_05
		RIF2012.INPATIENT_CLAIMS_06
		RIF2012.INPATIENT_CLAIMS_07
		RIF2012.INPATIENT_CLAIMS_08
		RIF2012.INPATIENT_CLAIMS_09
		RIF2012.INPATIENT_CLAIMS_10
		RIF2012.INPATIENT_CLAIMS_11
		RIF2012.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
DROP TABLE WORK.Hospital_Location;
CREATE TABLE WORK.Hospital_Location AS
	SELECT ORG_NPI_NUM AS Hosp_NPI, PRVDR_NUM AS Provider_Number,
		PRVDR_STATE_CD AS Hosp_State, SUBSTR(CLM_SRVC_FAC_ZIP_CD,1,5) AS Hosp_Zip,
		count(*) AS Claim_Count
	FROM WORK.InpatientStays_2012
	GROUP BY Hosp_NPI, PRVDR_NUM, Hosp_State, Hosp_Zip;
QUIT;

PROC SQL;
DROP TABLE PL027710.Hospital_Location_2012;
CREATE TABLE PL027710.Hospital_Location_2012 AS
	SELECT a.*, b.FAC_NAME AS Hosp_Name_POS, b.FIPS_CNTY_CD AS Hosp_County_POS, b.FIPS_STATE_CD AS Hosp_State_POS,
		b.PRVDR_NUM AS Provider_Number, b.PARENT_PROVIDER_NUMBER AS Parent_Provider_Number, b.ZIP_CD AS Hosp_Zip_POS
	FROM WORK.Hospital_Location AS a
	LEFT JOIN PROVIDER.POS_2012 AS b
	ON a.Provider_Number=b.PRVDR_NUM;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation1;
  CREATE TABLE WORK.PhyLocation1 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_01
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation2;
  CREATE TABLE WORK.PhyLocation2 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_02
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation3;
  CREATE TABLE WORK.PhyLocation3 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_03
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation4;
  CREATE TABLE WORK.PhyLocation4 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_04
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation5;
  CREATE TABLE WORK.PhyLocation5 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_05
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation6;
  CREATE TABLE WORK.PhyLocation6 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_06
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation7;
  CREATE TABLE WORK.PhyLocation7 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_07
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation8;
  CREATE TABLE WORK.PhyLocation8 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_08
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation9;
  CREATE TABLE WORK.PhyLocation9 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_09
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation10;
  CREATE TABLE WORK.PhyLocation10 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_10
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation11;
  CREATE TABLE WORK.PhyLocation11 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_11
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation12;
  CREATE TABLE WORK.PhyLocation12 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2012.BCARRIER_LINE_12
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

DATA WORK.PhyLocation;
	SET	WORK.PhyLocation1
  		WORK.PhyLocation2
		WORK.PhyLocation3
		WORK.PhyLocation4
		WORK.PhyLocation5
		WORK.PhyLocation6
		WORK.PhyLocation7
		WORK.PhyLocation8
		WORK.PhyLocation9
		WORK.PhyLocation10
		WORK.PhyLocation11
		WORK.PhyLocation12;
RUN;


PROC SQL;
  DROP TABLE PL027710.PhyLocation_2012;
  CREATE TABLE PL027710.PhyLocation_2012 AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;




/* ------------------------------------------------------------ 	*/
/* 2013 Data */
/* ------------------------------------------------------------ 	*/
DATA WORK.InpatientStays_2013;
	SET	RIF2013.INPATIENT_CLAIMS_01
  		RIF2013.INPATIENT_CLAIMS_02
		RIF2013.INPATIENT_CLAIMS_03
		RIF2013.INPATIENT_CLAIMS_04
		RIF2013.INPATIENT_CLAIMS_05
		RIF2013.INPATIENT_CLAIMS_06
		RIF2013.INPATIENT_CLAIMS_07
		RIF2013.INPATIENT_CLAIMS_08
		RIF2013.INPATIENT_CLAIMS_09
		RIF2013.INPATIENT_CLAIMS_10
		RIF2013.INPATIENT_CLAIMS_11
		RIF2013.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
DROP TABLE WORK.Hospital_Location;
CREATE TABLE WORK.Hospital_Location AS
	SELECT ORG_NPI_NUM AS Hosp_NPI, PRVDR_NUM AS Provider_Number,
		PRVDR_STATE_CD AS Hosp_State, SUBSTR(CLM_SRVC_FAC_ZIP_CD,1,5) AS Hosp_Zip,
		count(*) AS Claim_Count
	FROM WORK.InpatientStays_2013
	GROUP BY Hosp_NPI, PRVDR_NUM, Hosp_State, Hosp_Zip;
QUIT;

PROC SQL;
DROP TABLE PL027710.Hospital_Location_2013;
CREATE TABLE PL027710.Hospital_Location_2013 AS
	SELECT a.*, b.FAC_NAME AS Hosp_Name_POS, b.FIPS_CNTY_CD AS Hosp_County_POS, b.FIPS_STATE_CD AS Hosp_State_POS,
		b.PRVDR_NUM AS Provider_Number, b.PARENT_PROVIDER_NUMBER AS Parent_Provider_Number, b.ZIP_CD AS Hosp_Zip_POS
	FROM WORK.Hospital_Location AS a
	LEFT JOIN PROVIDER.POS_2013 AS b
	ON a.Provider_Number=b.PRVDR_NUM;
QUIT;


PROC SQL;
  DROP TABLE WORK.PhyLocation1;
  CREATE TABLE WORK.PhyLocation1 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_01
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation2;
  CREATE TABLE WORK.PhyLocation2 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_02
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation3;
  CREATE TABLE WORK.PhyLocation3 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_03
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation4;
  CREATE TABLE WORK.PhyLocation4 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_04
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation5;
  CREATE TABLE WORK.PhyLocation5 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_05
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation6;
  CREATE TABLE WORK.PhyLocation6 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_06
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation7;
  CREATE TABLE WORK.PhyLocation7 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_07
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation8;
  CREATE TABLE WORK.PhyLocation8 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_08
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation9;
  CREATE TABLE WORK.PhyLocation9 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_09
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation10;
  CREATE TABLE WORK.PhyLocation10 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_10
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation11;
  CREATE TABLE WORK.PhyLocation11 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_11
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation12;
  CREATE TABLE WORK.PhyLocation12 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2013.BCARRIER_LINE_12
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

DATA WORK.PhyLocation;
	SET	WORK.PhyLocation1
  		WORK.PhyLocation2
		WORK.PhyLocation3
		WORK.PhyLocation4
		WORK.PhyLocation5
		WORK.PhyLocation6
		WORK.PhyLocation7
		WORK.PhyLocation8
		WORK.PhyLocation9
		WORK.PhyLocation10
		WORK.PhyLocation11
		WORK.PhyLocation12;
RUN;


PROC SQL;
  DROP TABLE PL027710.PhyLocation_2013;
  CREATE TABLE PL027710.PhyLocation_2013 AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;


/* ------------------------------------------------------------ 	*/
/* 2014 Data */
/* ------------------------------------------------------------ 	*/
DATA WORK.InpatientStays_2014;
	SET	RIF2014.INPATIENT_CLAIMS_01
  		RIF2014.INPATIENT_CLAIMS_02
		RIF2014.INPATIENT_CLAIMS_03
		RIF2014.INPATIENT_CLAIMS_04
		RIF2014.INPATIENT_CLAIMS_05
		RIF2014.INPATIENT_CLAIMS_06
		RIF2014.INPATIENT_CLAIMS_07
		RIF2014.INPATIENT_CLAIMS_08
		RIF2014.INPATIENT_CLAIMS_09
		RIF2014.INPATIENT_CLAIMS_10
		RIF2014.INPATIENT_CLAIMS_11
		RIF2014.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
DROP TABLE WORK.Hospital_Location;
CREATE TABLE WORK.Hospital_Location AS
	SELECT ORG_NPI_NUM AS Hosp_NPI, PRVDR_NUM AS Provider_Number,
		PRVDR_STATE_CD AS Hosp_State, SUBSTR(CLM_SRVC_FAC_ZIP_CD,1,5) AS Hosp_Zip,
		count(*) AS Claim_Count
	FROM WORK.InpatientStays_2014
	GROUP BY Hosp_NPI, PRVDR_NUM, Hosp_State, Hosp_Zip;
QUIT;

PROC SQL;
DROP TABLE PL027710.Hospital_Location_2014;
CREATE TABLE PL027710.Hospital_Location_2014 AS
	SELECT a.*, b.FAC_NAME AS Hosp_Name_POS, b.FIPS_CNTY_CD AS Hosp_County_POS, b.FIPS_STATE_CD AS Hosp_State_POS,
		b.PRVDR_NUM AS Provider_Number, b.PARENT_PROVIDER_NUMBER AS Parent_Provider_Number, b.ZIP_CD AS Hosp_Zip_POS
	FROM WORK.Hospital_Location AS a
	LEFT JOIN PROVIDER.POS_2014 AS b
	ON a.Provider_Number=b.PRVDR_NUM;
QUIT;


PROC SQL;
  DROP TABLE WORK.PhyLocation1;
  CREATE TABLE WORK.PhyLocation1 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_01
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation2;
  CREATE TABLE WORK.PhyLocation2 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_02
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation3;
  CREATE TABLE WORK.PhyLocation3 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_03
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation4;
  CREATE TABLE WORK.PhyLocation4 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_04
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation5;
  CREATE TABLE WORK.PhyLocation5 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_05
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation6;
  CREATE TABLE WORK.PhyLocation6 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_06
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation7;
  CREATE TABLE WORK.PhyLocation7 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_07
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation8;
  CREATE TABLE WORK.PhyLocation8 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_08
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation9;
  CREATE TABLE WORK.PhyLocation9 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_09
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation10;
  CREATE TABLE WORK.PhyLocation10 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_10
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation11;
  CREATE TABLE WORK.PhyLocation11 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_11
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation12;
  CREATE TABLE WORK.PhyLocation12 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2014.BCARRIER_LINE_12
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

DATA WORK.PhyLocation;
	SET	WORK.PhyLocation1
  		WORK.PhyLocation2
		WORK.PhyLocation3
		WORK.PhyLocation4
		WORK.PhyLocation5
		WORK.PhyLocation6
		WORK.PhyLocation7
		WORK.PhyLocation8
		WORK.PhyLocation9
		WORK.PhyLocation10
		WORK.PhyLocation11
		WORK.PhyLocation12;
RUN;


PROC SQL;
  DROP TABLE PL027710.PhyLocation_2014;
  CREATE TABLE PL027710.PhyLocation_2014 AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;


/* ------------------------------------------------------------ 	*/
/* 2015 Data */
/* ------------------------------------------------------------ 	*/
DATA WORK.InpatientStays_2015;
	SET	RIF2015.INPATIENT_CLAIMS_01
  		RIF2015.INPATIENT_CLAIMS_02
		RIF2015.INPATIENT_CLAIMS_03
		RIF2015.INPATIENT_CLAIMS_04
		RIF2015.INPATIENT_CLAIMS_05
		RIF2015.INPATIENT_CLAIMS_06
		RIF2015.INPATIENT_CLAIMS_07
		RIF2015.INPATIENT_CLAIMS_08
		RIF2015.INPATIENT_CLAIMS_09
		RIF2015.INPATIENT_CLAIMS_10
		RIF2015.INPATIENT_CLAIMS_11
		RIF2015.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
DROP TABLE WORK.Hospital_Location;
CREATE TABLE WORK.Hospital_Location AS
	SELECT ORG_NPI_NUM AS Hosp_NPI, PRVDR_NUM AS Provider_Number,
		PRVDR_STATE_CD AS Hosp_State, SUBSTR(CLM_SRVC_FAC_ZIP_CD,1,5) AS Hosp_Zip,
		count(*) AS Claim_Count
	FROM WORK.InpatientStays_2015
	GROUP BY Hosp_NPI, PRVDR_NUM, Hosp_State, Hosp_Zip;
QUIT;

PROC SQL;
DROP TABLE PL027710.Hospital_Location_2015;
CREATE TABLE PL027710.Hospital_Location_2015 AS
	SELECT a.*, b.FAC_NAME AS Hosp_Name_POS, b.FIPS_CNTY_CD AS Hosp_County_POS, b.FIPS_STATE_CD AS Hosp_State_POS,
		b.PRVDR_NUM AS Provider_Number, b.PARENT_PROVIDER_NUMBER AS Parent_Provider_Number, b.ZIP_CD AS Hosp_Zip_POS
	FROM WORK.Hospital_Location AS a
	LEFT JOIN PROVIDER.POS_2015 AS b
	ON a.Provider_Number=b.PRVDR_NUM;
QUIT;


PROC SQL;
  DROP TABLE WORK.PhyLocation1;
  CREATE TABLE WORK.PhyLocation1 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_01
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation2;
  CREATE TABLE WORK.PhyLocation2 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_02
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation3;
  CREATE TABLE WORK.PhyLocation3 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_03
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation4;
  CREATE TABLE WORK.PhyLocation4 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_04
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation5;
  CREATE TABLE WORK.PhyLocation5 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_05
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation6;
  CREATE TABLE WORK.PhyLocation6 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_06
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation7;
  CREATE TABLE WORK.PhyLocation7 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_07
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation8;
  CREATE TABLE WORK.PhyLocation8 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_08
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation9;
  CREATE TABLE WORK.PhyLocation9 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_09
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation10;
  CREATE TABLE WORK.PhyLocation10 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_10
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation11;
  CREATE TABLE WORK.PhyLocation11 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_11
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation12;
  CREATE TABLE WORK.PhyLocation12 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2015.BCARRIER_LINE_12
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

DATA WORK.PhyLocation;
	SET	WORK.PhyLocation1
  		WORK.PhyLocation2
		WORK.PhyLocation3
		WORK.PhyLocation4
		WORK.PhyLocation5
		WORK.PhyLocation6
		WORK.PhyLocation7
		WORK.PhyLocation8
		WORK.PhyLocation9
		WORK.PhyLocation10
		WORK.PhyLocation11
		WORK.PhyLocation12;
RUN;


PROC SQL;
  DROP TABLE PL027710.PhyLocation_2015;
  CREATE TABLE PL027710.PhyLocation_2015 AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;


/* ------------------------------------------------------------ 	*/
/* 2016 Data */
/* ------------------------------------------------------------ 	*/
DATA WORK.InpatientStays_2016;
	SET	RIF2016.INPATIENT_CLAIMS_01
  		RIF2016.INPATIENT_CLAIMS_02
		RIF2016.INPATIENT_CLAIMS_03
		RIF2016.INPATIENT_CLAIMS_04
		RIF2016.INPATIENT_CLAIMS_05
		RIF2016.INPATIENT_CLAIMS_06
		RIF2016.INPATIENT_CLAIMS_07
		RIF2016.INPATIENT_CLAIMS_08
		RIF2016.INPATIENT_CLAIMS_09
		RIF2016.INPATIENT_CLAIMS_10
		RIF2016.INPATIENT_CLAIMS_11
		RIF2016.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
DROP TABLE WORK.Hospital_Location;
CREATE TABLE WORK.Hospital_Location AS
	SELECT ORG_NPI_NUM AS Hosp_NPI, PRVDR_NUM AS Provider_Number,
		PRVDR_STATE_CD AS Hosp_State, SUBSTR(CLM_SRVC_FAC_ZIP_CD,1,5) AS Hosp_Zip,
		count(*) AS Claim_Count
	FROM WORK.InpatientStays_2016
	GROUP BY Hosp_NPI, PRVDR_NUM, Hosp_State, Hosp_Zip;
QUIT;

PROC SQL;
DROP TABLE PL027710.Hospital_Location_2016;
CREATE TABLE PL027710.Hospital_Location_2016 AS
	SELECT a.*, b.FAC_NAME AS Hosp_Name_POS, b.FIPS_CNTY_CD AS Hosp_County_POS, b.FIPS_STATE_CD AS Hosp_State_POS,
		b.PRVDR_NUM AS Provider_Number, b.PARENT_PROVIDER_NUMBER AS Parent_Provider_Number, b.ZIP_CD AS Hosp_Zip_POS
	FROM WORK.Hospital_Location AS a
	LEFT JOIN PROVIDER.POS_2016 AS b
	ON a.Provider_Number=b.PRVDR_NUM;
QUIT;


PROC SQL;
  DROP TABLE WORK.PhyLocation1;
  CREATE TABLE WORK.PhyLocation1 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_01
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation2;
  CREATE TABLE WORK.PhyLocation2 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_02
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation3;
  CREATE TABLE WORK.PhyLocation3 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_03
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation4;
  CREATE TABLE WORK.PhyLocation4 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_04
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation5;
  CREATE TABLE WORK.PhyLocation5 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_05
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation6;
  CREATE TABLE WORK.PhyLocation6 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_06
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation7;
  CREATE TABLE WORK.PhyLocation7 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_07
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation8;
  CREATE TABLE WORK.PhyLocation8 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_08
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation9;
  CREATE TABLE WORK.PhyLocation9 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_09
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation10;
  CREATE TABLE WORK.PhyLocation10 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_10
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation11;
  CREATE TABLE WORK.PhyLocation11 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_11
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation12;
  CREATE TABLE WORK.PhyLocation12 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2016.BCARRIER_LINE_12
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

DATA WORK.PhyLocation;
	SET	WORK.PhyLocation1
  		WORK.PhyLocation2
		WORK.PhyLocation3
		WORK.PhyLocation4
		WORK.PhyLocation5
		WORK.PhyLocation6
		WORK.PhyLocation7
		WORK.PhyLocation8
		WORK.PhyLocation9
		WORK.PhyLocation10
		WORK.PhyLocation11
		WORK.PhyLocation12;
RUN;


PROC SQL;
  DROP TABLE PL027710.PhyLocation_2016;
  CREATE TABLE PL027710.PhyLocation_2016 AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;


/* ------------------------------------------------------------ 	*/
/* 2017 Data */
/* ------------------------------------------------------------ 	*/
DATA WORK.InpatientStays_2017;
	SET	RIF2017.INPATIENT_CLAIMS_01
  		RIF2017.INPATIENT_CLAIMS_02
		RIF2017.INPATIENT_CLAIMS_03
		RIF2017.INPATIENT_CLAIMS_04
		RIF2017.INPATIENT_CLAIMS_05
		RIF2017.INPATIENT_CLAIMS_06
		RIF2017.INPATIENT_CLAIMS_07
		RIF2017.INPATIENT_CLAIMS_08
		RIF2017.INPATIENT_CLAIMS_09
		RIF2017.INPATIENT_CLAIMS_10
		RIF2017.INPATIENT_CLAIMS_11
		RIF2017.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
DROP TABLE WORK.Hospital_Location;
CREATE TABLE WORK.Hospital_Location AS
	SELECT ORG_NPI_NUM AS Hosp_NPI, PRVDR_NUM AS Provider_Number,
		PRVDR_STATE_CD AS Hosp_State, SUBSTR(CLM_SRVC_FAC_ZIP_CD,1,5) AS Hosp_Zip,
		count(*) AS Claim_Count
	FROM WORK.InpatientStays_2017
	GROUP BY Hosp_NPI, PRVDR_NUM, Hosp_State, Hosp_Zip;
QUIT;

PROC SQL;
DROP TABLE PL027710.Hospital_Location_2017;
CREATE TABLE PL027710.Hospital_Location_2017 AS
	SELECT a.*, b.FAC_NAME AS Hosp_Name_POS, b.FIPS_CNTY_CD AS Hosp_County_POS, b.FIPS_STATE_CD AS Hosp_State_POS,
		b.PRVDR_NUM AS Provider_Number, b.PARENT_PROVIDER_NUMBER AS Parent_Provider_Number, b.ZIP_CD AS Hosp_Zip_POS
	FROM WORK.Hospital_Location AS a
	LEFT JOIN PROVIDER.POS_2017 AS b
	ON a.Provider_Number=b.PRVDR_NUM;
QUIT;



PROC SQL;
  DROP TABLE WORK.PhyLocation1;
  CREATE TABLE WORK.PhyLocation1 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_01
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation2;
  CREATE TABLE WORK.PhyLocation2 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_02
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation3;
  CREATE TABLE WORK.PhyLocation3 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_03
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation4;
  CREATE TABLE WORK.PhyLocation4 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_04
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation5;
  CREATE TABLE WORK.PhyLocation5 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_05
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation6;
  CREATE TABLE WORK.PhyLocation6 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_06
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation7;
  CREATE TABLE WORK.PhyLocation7 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_07
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation8;
  CREATE TABLE WORK.PhyLocation8 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_08
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation9;
  CREATE TABLE WORK.PhyLocation9 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_09
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation10;
  CREATE TABLE WORK.PhyLocation10 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_10
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation11;
  CREATE TABLE WORK.PhyLocation11 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_11
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation12;
  CREATE TABLE WORK.PhyLocation12 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2017.BCARRIER_LINE_12
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

DATA WORK.PhyLocation;
	SET	WORK.PhyLocation1
  		WORK.PhyLocation2
		WORK.PhyLocation3
		WORK.PhyLocation4
		WORK.PhyLocation5
		WORK.PhyLocation6
		WORK.PhyLocation7
		WORK.PhyLocation8
		WORK.PhyLocation9
		WORK.PhyLocation10
		WORK.PhyLocation11
		WORK.PhyLocation12;
RUN;


PROC SQL;
  DROP TABLE PL027710.PhyLocation_2017;
  CREATE TABLE PL027710.PhyLocation_2017 AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;


/* ------------------------------------------------------------ 	*/
/* 2018 Data */
/* ------------------------------------------------------------ 	*/
DATA WORK.InpatientStays_2018;
	SET	RIF2018.INPATIENT_CLAIMS_01
  		RIF2018.INPATIENT_CLAIMS_02
		RIF2018.INPATIENT_CLAIMS_03
		RIF2018.INPATIENT_CLAIMS_04
		RIF2018.INPATIENT_CLAIMS_05
		RIF2018.INPATIENT_CLAIMS_06
		RIF2018.INPATIENT_CLAIMS_07
		RIF2018.INPATIENT_CLAIMS_08
		RIF2018.INPATIENT_CLAIMS_09
		RIF2018.INPATIENT_CLAIMS_10
		RIF2018.INPATIENT_CLAIMS_11
		RIF2018.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
DROP TABLE WORK.Hospital_Location;
CREATE TABLE WORK.Hospital_Location AS
	SELECT ORG_NPI_NUM AS Hosp_NPI, PRVDR_NUM AS Provider_Number,
		PRVDR_STATE_CD AS Hosp_State, SUBSTR(CLM_SRVC_FAC_ZIP_CD,1,5) AS Hosp_Zip,
		count(*) AS Claim_Count
	FROM WORK.InpatientStays_2018
	GROUP BY Hosp_NPI, PRVDR_NUM, Hosp_State, Hosp_Zip;
QUIT;

PROC SQL;
DROP TABLE PL027710.Hospital_Location_2018;
CREATE TABLE PL027710.Hospital_Location_2018 AS
	SELECT a.*, b.FAC_NAME AS Hosp_Name_POS, b.FIPS_CNTY_CD AS Hosp_County_POS, b.FIPS_STATE_CD AS Hosp_State_POS,
		b.PRVDR_NUM AS Provider_Number, b.PARENT_PROVIDER_NUMBER AS Parent_Provider_Number, b.ZIP_CD AS Hosp_Zip_POS
	FROM WORK.Hospital_Location AS a
	LEFT JOIN PROVIDER.POS_2018 AS b
	ON a.Provider_Number=b.PRVDR_NUM;
QUIT;


PROC SQL;
  DROP TABLE WORK.PhyLocation1;
  CREATE TABLE WORK.PhyLocation1 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_01
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation2;
  CREATE TABLE WORK.PhyLocation2 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_02
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation3;
  CREATE TABLE WORK.PhyLocation3 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_03
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation4;
  CREATE TABLE WORK.PhyLocation4 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_04
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation5;
  CREATE TABLE WORK.PhyLocation5 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_05
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation6;
  CREATE TABLE WORK.PhyLocation6 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_06
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation7;
  CREATE TABLE WORK.PhyLocation7 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_07
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation8;
  CREATE TABLE WORK.PhyLocation8 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_08
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation9;
  CREATE TABLE WORK.PhyLocation9 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_09
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation10;
  CREATE TABLE WORK.PhyLocation10 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_10
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation11;
  CREATE TABLE WORK.PhyLocation11 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_11
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

PROC SQL;
  DROP TABLE WORK.PhyLocation12;
  CREATE TABLE WORK.PhyLocation12 AS
  SELECT PRF_PHYSN_NPI, SUBSTR(PRVDR_ZIP,1,5) as Phy_Zip_Perf, SUBSTR(PHYSN_ZIP_CD, 1, 5) as Phy_Zip_POS, count(*) AS Claim_Count
  FROM RIF2018.BCARRIER_LINE_12
  GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf, Phy_Zip_POS;
QUIT;

DATA WORK.PhyLocation;
	SET	WORK.PhyLocation1
  		WORK.PhyLocation2
		WORK.PhyLocation3
		WORK.PhyLocation4
		WORK.PhyLocation5
		WORK.PhyLocation6
		WORK.PhyLocation7
		WORK.PhyLocation8
		WORK.PhyLocation9
		WORK.PhyLocation10
		WORK.PhyLocation11
		WORK.PhyLocation12;
RUN;


PROC SQL;
  DROP TABLE PL027710.PhyLocation_2018;
  CREATE TABLE PL027710.PhyLocation_2018 AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;



PROC SQL;
  DROP TABLE PL027710.PhyLocation_2018_test;
  CREATE TABLE PL027710.PhyLocation_2018_test AS
  SELECT DISTINCT a.PRF_PHYSN_NPI AS Physician_NPI, b.Phy_Zip_Perf, b.Claims_Perf,
  	c.Phy_Zip_POS, c.Claims_POS
  FROM WORK.PhyLocation12 AS a
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_Perf, sum(Claim_Count) AS Claims_Perf
  			 FROM WORK.PhyLocation12
			 WHERE Phy_Zip_Perf IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_Perf) AS b
		ON a.PRF_PHYSN_NPI=b.PRF_PHYSN_NPI
  LEFT JOIN (SELECT PRF_PHYSN_NPI, Phy_Zip_POS, sum(Claim_Count) AS Claims_POS
  			 FROM WORK.PhyLocation12
			 WHERE Phy_Zip_POS IS NOT NULL
			 GROUP BY PRF_PHYSN_NPI, Phy_Zip_POS) AS c
		ON a.PRF_PHYSN_NPI=c.PRF_PHYSN_NPI
  WHERE Physician_NPI IS NOT NULL;
QUIT;



PROC SQL;
	DROP TABLE PL027710.BENE_Data_2009;
	CREATE TABLE PL027710.BENE_Data_2009 AS
		SELECT BENE_ID, ZIP_CD AS BENE_ZIP, BENE_BIRTH_DT, BENE_DEATH_DT, SEX_IDENT_CD AS BENE_Gender, BENE_RACE_CD AS BENE_Race
		FROM MBSF.MBSF_ABCD_2009;
QUIT;


PROC SQL;
	DROP TABLE PL027710.BENE_Data_2010;
	CREATE TABLE PL027710.BENE_Data_2010 AS
		SELECT BENE_ID, ZIP_CD AS BENE_ZIP, BENE_BIRTH_DT, BENE_DEATH_DT, SEX_IDENT_CD AS BENE_Gender, BENE_RACE_CD AS BENE_Race
		FROM MBSF.MBSF_ABCD_2010;
QUIT;


PROC SQL;
	DROP TABLE PL027710.BENE_Data_2011;
	CREATE TABLE PL027710.BENE_Data_2011 AS
		SELECT BENE_ID, ZIP_CD AS BENE_ZIP, BENE_BIRTH_DT, BENE_DEATH_DT, SEX_IDENT_CD AS BENE_Gender, BENE_RACE_CD AS BENE_Race
		FROM MBSF.MBSF_ABCD_2011;
QUIT;

PROC SQL;
	DROP TABLE PL027710.BENE_Data_2012;
	CREATE TABLE PL027710.BENE_Data_2012 AS
		SELECT BENE_ID, ZIP_CD AS BENE_ZIP, BENE_BIRTH_DT, BENE_DEATH_DT, SEX_IDENT_CD AS BENE_Gender, BENE_RACE_CD AS BENE_Race
		FROM MBSF.MBSF_ABCD_2012;
QUIT;


PROC SQL;
	DROP TABLE PL027710.BENE_Data_2013;
	CREATE TABLE PL027710.BENE_Data_2013 AS
		SELECT BENE_ID, ZIP_CD AS BENE_ZIP, BENE_BIRTH_DT, BENE_DEATH_DT, SEX_IDENT_CD AS BENE_Gender, BENE_RACE_CD AS BENE_Race
		FROM MBSF.MBSF_ABCD_2013;
QUIT;

PROC SQL;
	DROP TABLE PL027710.BENE_Data_2014;
	CREATE TABLE PL027710.BENE_Data_2014 AS
		SELECT BENE_ID, ZIP_CD AS BENE_ZIP, BENE_BIRTH_DT, BENE_DEATH_DT, SEX_IDENT_CD AS BENE_Gender, BENE_RACE_CD AS BENE_Race
		FROM MBSF.MBSF_ABCD_2014;
QUIT;

PROC SQL;
	DROP TABLE PL027710.BENE_Data_2015;
	CREATE TABLE PL027710.BENE_Data_2015 AS
		SELECT BENE_ID, ZIP_CD AS BENE_ZIP, BENE_BIRTH_DT, BENE_DEATH_DT, SEX_IDENT_CD AS BENE_Gender, BENE_RACE_CD AS BENE_Race
		FROM MBSF.MBSF_ABCD_2015;
QUIT;

PROC SQL;
	DROP TABLE PL027710.BENE_Data_2016;
	CREATE TABLE PL027710.BENE_Data_2016 AS
		SELECT BENE_ID, ZIP_CD AS BENE_ZIP, BENE_BIRTH_DT, BENE_DEATH_DT, SEX_IDENT_CD AS BENE_Gender, BENE_RACE_CD AS BENE_Race
		FROM MBSF.MBSF_ABCD_2016;
QUIT;

PROC SQL;
	DROP TABLE PL027710.BENE_Data_2017;
	CREATE TABLE PL027710.BENE_Data_2017 AS
		SELECT BENE_ID, ZIP_CD AS BENE_ZIP, BENE_BIRTH_DT, BENE_DEATH_DT, SEX_IDENT_CD AS BENE_Gender, BENE_RACE_CD AS BENE_Race
		FROM MBSF.MBSF_ABCD_2017;
QUIT;


PROC SQL;
	DROP TABLE PL027710.BENE_Data_2018;
	CREATE TABLE PL027710.BENE_Data_2018 AS
		SELECT BENE_ID, ZIP_CD AS BENE_ZIP, BENE_BIRTH_DT, BENE_DEATH_DT, SEX_IDENT_CD AS BENE_Gender, BENE_RACE_CD AS BENE_Race
		FROM MBSF.MBSF_ABCD_2018;
QUIT;
