/* ------------------------------------------------------------ */
/* TITLE:		 Supplemental Physician Data			        */
/* AUTHOR:		 Ian McCarthy									*/
/* 				 Emory University								*/
/* DATE CREATED: 5/12/2015										*/
/* DATE EDITED:  8/9/2017										*/
/* CODE FILE ORDER: Supplemental								*/
/* NOTES:														*/
/*   BENE_CC  Master beneficiary summary file 					*/
/*   MCBSxxxx Medicare Current Beneficiary Survey (Year xxxx) 	*/
/*   MCBSXWLK MCBS Crosswalk 									*/
/*   RIFSxxxx Out/Inpatient and Carrier claims (Year xxxx)  	*/
/*   Medpar   Inpatient claims  								*/
/*     -- Updated on 4/5/16 to include case statement in NPPES  */
/*   -- File outputs the following tables to PL027710:			*/
/*		NPPES_All												*/
/* ------------------------------------------------------------ */


PROC SQL;
	DROP TABLE PL027710.NPPES_2007;
	CREATE TABLE PL027710.NPPES_2007 AS
	SELECT *, 
		CASE
			WHEN HPPTS_1='Y' THEN HPTC_1
			WHEN HPPTS_2='Y' THEN HPTC_2
			WHEN HPPTS_3='Y' THEN HPTC_3
			WHEN HPPTS_4='Y' THEN HPTC_4
			WHEN HPPTS_5='Y' THEN HPTC_5
			ELSE ''
		END AS Specialty_HPTC, 2007 AS Year
    FROM NPPES10.NPPES_DEC2010;
QUIT;

PROC SQL;
	DROP TABLE PL027710.NPPES_2008;
	CREATE TABLE PL027710.NPPES_2008 AS
	SELECT *, 
		CASE
			WHEN HPPTS_1='Y' THEN HPTC_1
			WHEN HPPTS_2='Y' THEN HPTC_2
			WHEN HPPTS_3='Y' THEN HPTC_3
			WHEN HPPTS_4='Y' THEN HPTC_4
			WHEN HPPTS_5='Y' THEN HPTC_5
			ELSE ''
		END AS Specialty_HPTC, 2008 AS Year
    FROM NPPES10.NPPES_DEC2010;
QUIT;

PROC SQL;
	DROP TABLE PL027710.NPPES_2009;
	CREATE TABLE PL027710.NPPES_2009 AS
	SELECT *, 
		CASE
			WHEN HPPTS_1='Y' THEN HPTC_1
			WHEN HPPTS_2='Y' THEN HPTC_2
			WHEN HPPTS_3='Y' THEN HPTC_3
			WHEN HPPTS_4='Y' THEN HPTC_4
			WHEN HPPTS_5='Y' THEN HPTC_5
			ELSE ''
		END AS Specialty_HPTC, 2009 AS Year
    FROM NPPES10.NPPES_DEC2010;
QUIT;


PROC SQL;
	DROP TABLE PL027710.NPPES_2010;
	CREATE TABLE PL027710.NPPES_2010 AS
	SELECT *, 
		CASE
			WHEN HPPTS_1='Y' THEN HPTC_1
			WHEN HPPTS_2='Y' THEN HPTC_2
			WHEN HPPTS_3='Y' THEN HPTC_3
			WHEN HPPTS_4='Y' THEN HPTC_4
			WHEN HPPTS_5='Y' THEN HPTC_5
			ELSE ''
		END AS Specialty_HPTC, 2010 AS Year
    FROM NPPES10.NPPES_DEC2010;
QUIT;

PROC SQL;
	DROP TABLE PL027710.NPPES_2011;
	CREATE TABLE PL027710.NPPES_2011 AS
	SELECT *, 
		CASE
			WHEN HPPTS_1='Y' THEN HPTC_1
			WHEN HPPTS_2='Y' THEN HPTC_2
			WHEN HPPTS_3='Y' THEN HPTC_3
			WHEN HPPTS_4='Y' THEN HPTC_4
			WHEN HPPTS_5='Y' THEN HPTC_5
			ELSE ''
		END AS Specialty_HPTC, 2011 AS Year
    FROM NPPES11.NPPES_DEC2011;
QUIT;

PROC SQL;
	DROP TABLE PL027710.NPPES_2012;
	CREATE TABLE PL027710.NPPES_2012 AS
	SELECT *, 
		CASE
			WHEN HPPTS_1='Y' THEN HPTC_1
			WHEN HPPTS_2='Y' THEN HPTC_2
			WHEN HPPTS_3='Y' THEN HPTC_3
			WHEN HPPTS_4='Y' THEN HPTC_4
			WHEN HPPTS_5='Y' THEN HPTC_5
			ELSE ''
		END AS Specialty_HPTC, 2012 AS Year
    FROM NPPES12.NPPES_DEC2012;
QUIT;

PROC SQL;
	DROP TABLE PL027710.NPPES_2013;
	CREATE TABLE PL027710.NPPES_2013 AS
	SELECT *, 
		CASE
			WHEN HPPTS_1='Y' THEN HPTC_1
			WHEN HPPTS_2='Y' THEN HPTC_2
			WHEN HPPTS_3='Y' THEN HPTC_3
			WHEN HPPTS_4='Y' THEN HPTC_4
			WHEN HPPTS_5='Y' THEN HPTC_5
			ELSE ''
		END AS Specialty_HPTC, 2013 AS Year
    FROM NPPES13.NPPES_DEC2013;
QUIT;

PROC SQL;
	DROP TABLE PL027710.NPPES_2014;
	CREATE TABLE PL027710.NPPES_2014 AS
	SELECT *, 
		CASE
			WHEN HPPTS_1='Y' THEN HPTC_1
			WHEN HPPTS_2='Y' THEN HPTC_2
			WHEN HPPTS_3='Y' THEN HPTC_3
			WHEN HPPTS_4='Y' THEN HPTC_4
			WHEN HPPTS_5='Y' THEN HPTC_5
			ELSE ''
		END AS Specialty_HPTC, 2014 AS Year
    FROM NPPES14.NPPES_DEC2014;
QUIT;

PROC SQL;
	DROP TABLE PL027710.NPPES_2015;
	CREATE TABLE PL027710.NPPES_2015 AS
	SELECT *, 
		CASE
			WHEN HPPTS_1='Y' THEN HPTC_1
			WHEN HPPTS_2='Y' THEN HPTC_2
			WHEN HPPTS_3='Y' THEN HPTC_3
			WHEN HPPTS_4='Y' THEN HPTC_4
			WHEN HPPTS_5='Y' THEN HPTC_5
			ELSE ''
		END AS Specialty_HPTC, 2015 AS Year
    FROM NPPES15.NPPES_DEC2015;
QUIT;
